version: "3"
services:
  prom:
    container_name: prom
    image: prom/prometheus
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
     - 9090:9090
    depends_on:
     - exporter
  exporter:
    container_name: exporter
    image: prom/node-exporter:latest
    ports:
     - "9091:9100"
#    network_mode: host
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
     - "9091:3000"
    depends_on:
      - prom
